---
server:
  port: 8888
security:
  basic:
    enabled: false
  #user:
    #name: pluralsight
    #password: pluralsight
  
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/willkzhou/toll-station-system-tolls # default
          #username: abc
          #password: abc
          search-paths:
            - 'station*'
          repos:
             perf:
                pattern: '*/perf'
                uri: https://github.com/willkzhou/toll-station-system-tolls-perf  # perfomance repo
                search-paths:
                 - 'station*'
